# Task 1: Iris Flower Classification

In [ ]:
# importing libraries

import sklearn as sk
import tensorflow as tf
import pandas as pd

In [ ]:
# Creating dataframe from the dataset imported form local drive
iris_df = pd.read_csv("/content/Iris.csv")

In [ ]:
iris_df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
# Splitting dataset into X and y (independent and dependent variables)
X = iris_df[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
Y = iris_df["Species"]

In [ ]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [ ]:
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
X.shape, Y.shape

((150, 4), (150,))

In [ ]:
# Using sklearn for creating train_test split of dateset
# 80 % -> train_data
# 20 % -> test_data

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [ ]:
X_train.shape, X_test.shape

((120, 4), (30, 4))

In [ ]:
y_train.shape, y_test.shape

((120,), (30,))

In [ ]:
X_train_numpy = X_train.to_numpy()

In [ ]:
X_train_numpy.dtype

dtype('float64')

In [ ]:
X_train_tensor = tf.constant(X_train)

In [ ]:
X_train_tensor[:10]

<tf.Tensor: shape=(10, 4), dtype=float64, numpy=
array([[4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1]])>

In [ ]:
y_train_tensor = tf.constant(y_train)

In [ ]:
y_train_tensor[:10]

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor', b'Iris-setosa',
       b'Iris-setosa', b'Iris-virginica', b'Iris-versicolor',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'], dtype=object)>

In [ ]:
X_test_tensor = tf.constant(X_test)

In [ ]:
X_test_tensor[:10]

<tf.Tensor: shape=(10, 4), dtype=float64, numpy=
array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2]])>

In [ ]:
y_test_tensor = tf.constant(y_test)

In [ ]:
y_test_tensor[:10]

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'Iris-versicolor', b'Iris-setosa', b'Iris-virginica',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-setosa',
       b'Iris-versicolor', b'Iris-virginica', b'Iris-versicolor',
       b'Iris-versicolor'], dtype=object)>

In [ ]:
y_train_tensor.dtype

tf.string

In [ ]:
# converting categorical string data into numeric python data using get_dummies()

y_dummy_train_tensor = pd.get_dummies(y_train_tensor)

In [ ]:
y_dummy_train_tensor[:10]

b'Iris-setosa'  b'Iris-versicolor'  b'Iris-virginica'
0               1                   0                  0
1               1                   0                  0
2               0                   1                  0
3               1                   0                  0
4               1                   0                  0
5               0                   0                  1
6               0                   1                  0
7               1                   0                  0
8               1                   0                  0
9               1                   0                  0

In [ ]:
# # converting categorical string data into numeric python data using get_dummies()

y_dummy_test_tensor = pd.get_dummies(y_test_tensor)

In [ ]:
y_dummy_test_tensor[:10]

b'Iris-setosa'  b'Iris-versicolor'  b'Iris-virginica'
0               0                   1                  0
1               1                   0                  0
2               0                   0                  1
3               0                   1                  0
4               0                   1                  0
5               1                   0                  0
6               0                   1                  0
7               0                   0                  1
8               0                   1                  0
9               0                   1                  0

### Model Creation using tf Sequential Api

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dense(64, activation = "relu"),
    tf.keras.layers.Dense(3, activation = "softmax")
])

model.compile(loss = "categorical_crossentropy",
              optimizer = tf.keras.optimizers.Adam(),
              metrics = ["accuracy"])

model.fit(X_train_tensor, y_dummy_train_tensor,
          epochs = 20)


Epoch 1/20
4/4 [==============================] - 1s 5ms/step - loss: 0.9133 - accuracy: 0.6583
Epoch 2/20
4/4 [==============================] - 0s 3ms/step - loss: 0.7759 - accuracy: 0.8583
Epoch 3/20
4/4 [==============================] - 0s 3ms/step - loss: 0.6813 - accuracy: 0.8500
Epoch 4/20
4/4 [==============================] - 0s 6ms/step - loss: 0.6169 - accuracy: 0.7750
Epoch 5/20
4/4 [==============================] - 0s 4ms/step - loss: 0.5562 - accuracy: 0.8833
Epoch 6/20
4/4 [==============================] - 0s 3ms/step - loss: 0.5070 - accuracy: 0.9333
Epoch 7/20
4/4 [==============================] - 0s 3ms/step - loss: 0.4667 - accuracy: 0.9417
Epoch 8/20
4/4 [==============================] - 0s 4ms/step - loss: 0.4317 - accuracy: 0.9500
Epoch 9/20
4/4 [==============================] - 0s 4ms/step - loss: 0.4016 - accuracy: 0.9417
Epoch 10/20
4/4 [==============================] - 0s 4ms/step - loss: 0.3782 - accuracy: 0.9333
Epoch 11/20
4/4 [======================

In [ ]:
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_42 (Dense)            (None, 128)               640       
                                                                 
 dense_43 (Dense)            (None, 64)                8256      
                                                                 
 dense_44 (Dense)            (None, 3)                 195       
                                                                 
Total params: 9,091
Trainable params: 9,091
Non-trainable params: 0
_________________________________________________________________


### Evaluating the model on test data set

In [ ]:
model.evaluate(X_test_tensor, y_dummy_test_tensor)

1/1 [==============================] - 0s 284ms/step - loss: 0.2281 - accuracy: 1.0000


[0.22810842096805573, 1.0]